### ISSUE TITLE
Playback error: source error (2000): Unexpected P: File size

### ISSUE THREAD

**Issue by MoseySlu** [OuterTune/OuterTune#119]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/dd3boh/OuterTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [x] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Log in with Google account
2. Tap on song to play it/Download it

### Expected behavior

Should start playing the song and also be able to download it.

### Actual behavior

When I try to play a specific song, it shows an error "Playback error: source error (2000): Unexpected P: File size". When I try downloading it, it shows the downloading in progress animation but never finishes. In case of testing, it's called "A Sky Full Of Stars" from Persona 4.

I tested from other devices the same song without signing in to any account and it shows the same error, so it probably isn't an issue with my device.

### Logs

N/A

### OuterTune version

0.63 (24) | universal

### Android version

Android 14 (One UI 6.1)

**Comment by HafizBeyy** [comment]
its the same happening when try to play local audio on my device **lineage os 21** at version **0.7.3_rev1**.
please fix this issue.

**Comment by ghost** [comment]
Same issue, I cant play or download one specific song
```
type: logcat
osVersion: google/tokay/tokay:15/AP4A.250205.002/2025030300:user/release-keys
package: com.dd3boh.outertune.debug:39, targetSdk 35
buffers: main,system,crash,events,kernel
level: error

--------- beginning of main
03-07 18:56:38.688 27877 27918 E DownloadManager: Task failed: null:LAGvNEQvrp4, false
03-07 18:56:38.688 27877 27918 E DownloadManager:   androidx.media3.common.PlaybackException: Local song are non-downloadable
03-07 18:56:38.688 27877 27918 E DownloadManager:       at com.dd3boh.outertune.playback.DownloadUtil.dataSourceFactory$lambda$4(DownloadUtil.kt:66)
03-07 18:56:38.688 27877 27918 E DownloadManager:       at com.dd3boh.outertune.playback.DownloadUtil.$r8$lambda$W6-Tpe5mq9loTkAJroFeENIXdp4(Unknown Source:0)
03-07 18:56:38.688 27877 27918 E DownloadManager:       at com.dd3boh.outertune.playback.DownloadUtil$$ExternalSyntheticLambda1.resolveDataSpec(D8$$SyntheticClass:0)
03-07 18:56:38.688 27877 27918 E DownloadManager:       at androidx.media3.datasource.ResolvingDataSource.open(ResolvingDataSource.java:108)
03-07 18:56:38.688 27877 27918 E DownloadManager:       at androidx.media3.datasource.TeeDataSource.open(TeeDataSource.java:54)
03-07 18:56:38.688 27877 27918 E DownloadManager:       at androidx.media3.datasource.cache.CacheDataSource.openNextSource(CacheDataSource.java:802)
03-07 18:56:38.688 27877 27918 E DownloadManager:       at androidx.media3.datasource.cache.CacheDataSource.open(CacheDataSource.java:615)
03-07 18:56:38.688 27877 27918 E DownloadManager:       at androidx.media3.datasource.cache.CacheWriter.readBlockToCache(CacheWriter.java:174)
03-07 18:56:38.688 27877 27918 E DownloadManager:       at androidx.media3.datasource.cache.CacheWriter.cache(CacheWriter.java:136)
03-07 18:56:38.688 27877 27918 E DownloadManager:       at androidx.media3.exoplayer.offline.ProgressiveDownloader$1.doWork(ProgressiveDownloader.java:106)
03-07 18:56:38.688 27877 27918 E DownloadManager:       at androidx.media3.exoplayer.offline.ProgressiveDownloader$1.doWork(ProgressiveDownloader.java:103)
03-07 18:56:38.688 27877 27918 E DownloadManager:       at androidx.media3.common.util.RunnableFutureTask.run(RunnableFutureTask.java:126)
03-07 18:56:38.688 27877 27918 E DownloadManager:       at com.dd3boh.outertune.playback.DownloadUtil$$ExternalSyntheticLambda2.execute(D8$$SyntheticClass:0)
03-07 18:56:38.688 27877 27918 E DownloadManager:       at androidx.media3.exoplayer.offline.ProgressiveDownloader.download(ProgressiveDownloader.java:118)
03-07 18:56:38.688 27877 27918 E DownloadManager:       at androidx.media3.exoplayer.offline.DownloadManager$Task.run(DownloadManager.java:1343)
03-07 18:57:36.801 28274 28353 E LoadTask: Unexpected exception loading stream
03-07 18:57:36.801 28274 28353 E LoadTask:   androidx.media3.common.PlaybackException: File size
03-07 18:57:36.801 28274 28353 E LoadTask:       at com.dd3boh.outertune.playback.MusicService.createDataSourceFactory$lambda$30(MusicService.kt:795)
03-07 18:57:36.801 28274 28353 E LoadTask:       at com.dd3boh.outertune.playback.MusicService.$r8$lambda$MytZOKV6xo4_XO3wbWLz9WmtjNk(Unknown Source:0)
03-07 18:57:36.801 28274 28353 E LoadTask:       at com.dd3boh.outertune.playback.MusicService$$ExternalSyntheticLambda0.resolveDataSpec(D8$$SyntheticClass:0)
03-07 18:57:36.801 28274 28353 E LoadTask:       at androidx.media3.datasource.ResolvingDataSource.open(ResolvingDataSource.java:108)
03-07 18:57:36.801 28274 28353 E LoadTask:       at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:87)
03-07 18:57:36.801 28274 28353 E LoadTask:       at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1085)
03-07 18:57:36.801 28274 28353 E LoadTask:       at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:450)
03-07 18:57:36.801 28274 28353 E LoadTask:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
03-07 18:57:36.801 28274 28353 E LoadTask:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
03-07 18:57:36.801 28274 28353 E LoadTask:       at java.lang.Thread.run(Thread.java:1117)
03-07 18:57:36.801 28274 28353 E LoadTask:   Caused by: java.lang.Throwable
03-07 18:57:36.801 28274 28353 E LoadTask:       at com.dd3boh.outertune.playback.MusicService.createDataSourceFactory$lambda$30(MusicService.kt:797)
03-07 18:57:36.801 28274 28353 E LoadTask:       ... 9 more
03-07 18:57:36.832 28274 28314 E ExoPlayerImplInternal: Playback error
03-07 18:57:36.832 28274 28314 E ExoPlayerImplInternal:   androidx.media3.exoplayer.ExoPlaybackException: Source error
03-07 18:57:36.832 28274 28314 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:737)
03-07 18:57:36.832 28274 28314 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:713)
03-07 18:57:36.832 28274 28314 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:105)
03-07 18:57:36.832 28274 28314 E ExoPlayerImplInternal:       at android.os.Looper.loopOnce(Looper.java:232)
03-07 18:57:36.832 28274 28314 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:317)
03-07 18:57:36.832 28274 28314 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:85)
03-07 18:57:36.832 28274 28314 E ExoPlayerImplInternal:   Caused by: androidx.media3.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected PlaybackException: File size
03-07 18:57:36.832 28274 28314 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:471)
03-07 18:57:36.832 28274 28314 E ExoPlayerImplInternal:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
03-07 18:57:36.832 28274 28314 E ExoPlayerImplInternal:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
03-07 18:57:36.832 28274 28314 E ExoPlayerImplInternal:       at java.lang.Thread.run(Thread.java:1117)
03-07 18:57:36.832 28274 28314 E ExoPlayerImplInternal:   Caused by: androidx.media3.common.PlaybackException: File size
03-07 18:57:36.832 28274 28314 E ExoPlayerImplInternal:       at com.dd3boh.outertune.playback.MusicService.createDataSourceFactory$lambda$30(MusicService.kt:795)
03-07 18:57:36.832 28274 28314 E ExoPlayerImplInternal:       at com.dd3boh.outertune.playback.MusicService.$r8$lambda$MytZOKV6xo4_XO3wbWLz9WmtjNk(Unknown Source:0)
03-07 18:57:36.832 28274 28314 E ExoPlayerImplInternal:       at com.dd3boh.outertune.playback.MusicService$$ExternalSyntheticLambda0.resolveDataSpec(D8$$SyntheticClass:0)
03-07 18:57:36.832 28274 28314 E ExoPlayerImplInternal:       at androidx.media3.datasource.ResolvingDataSource.open(ResolvingDataSource.java:108)
03-07 18:57:36.832 28274 28314 E ExoPlayerImplInternal:       at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:87)
03-07 18:57:36.832 28274 28314 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1085)
03-07 18:57:36.832 28274 28314 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:450)
03-07 18:57:36.832 28274 28314 E ExoPlayerImplInternal:       ... 3 more
03-07 18:57:36.832 28274 28314 E ExoPlayerImplInternal:   Caused by: java.lang.Throwable
03-07 18:57:36.832 28274 28314 E ExoPlayerImplInternal:       at com.dd3boh.outertune.playback.MusicService.createDataSourceFactory$lambda$30(MusicService.kt:797)
03-07 18:57:36.832 28274 28314 E ExoPlayerImplInternal:       ... 9 more
```

**Comment by SkyExploreWasTaken** [comment]
Happens also to me, hope they'll fix it

**Comment by Numerosityy** [comment]
Happens to me as well, except with "Unexpected Q: Unknown Error" as well

**Comment by 7032x** [comment]
Me too : "Error: Source error (2000): Unexpected Q: Erreur inconnue"
