### ISSUE TITLE
crash due to it tried to connect to youtube when I play offline songs and on an internet where youtube is blocked

### ISSUE THREAD

**Issue by inolie** [OuterTune/OuterTune#177]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/dd3boh/OuterTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

when i play any song (already downloaded), it crashed at 13 seconds. the song stopped, the phone goes to the home screen and outer tune player is still in the task manager. when i open tune player again from the task manager, the song is back to 0:00,

if i slide the progress bar to start play at any interval, it still crashes after playing for 13 seconds.

**I found that the error/crash does not occur when I completely turn off wifi or when the wifi is on but no internet connected. It ONLY happens when I am on an internet where youtube is blocked. Looking at the crash report it seems to be related to that the app is trying to connect to youtube (it shouldn't, since i am playing a song that is already downloaded. or the timeout error should be suppressed)**

### Expected behavior

not crash

### Actual behavior

crash

### Logs

--------- beginning of crash
12-24 15:39:36.030 10163 14628 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-22
12-24 15:39:36.030 10163 14628 E AndroidRuntime: Process: com.dd3boh.outertune, PID: 10163
12-24 15:39:36.030 10163 14628 E AndroidRuntime: t4.a: Connect timeout has expired [url=https://music.youtube.com/api/stats/playback?cl=******************************, connect_timeout=unknown ms]
12-24 15:39:36.030 10163 14628 E AndroidRuntime: 	at N2.a.m(SourceFile:114)
12-24 15:39:36.030 10163 14628 E AndroidRuntime: 	at O5.f.run(SourceFile:136)
12-24 15:39:36.030 10163 14628 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-24 15:39:36.030 10163 14628 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-24 15:39:36.030 10163 14628 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
12-24 15:39:36.030 10163 14628 E AndroidRuntime: 	Suppressed: x5.g: [z0{Cancelling}@6bac5ea, Dispatchers.IO]
12-24 15:39:36.030 10163 14628 E AndroidRuntime: Caused by: java.net.SocketTimeoutException: failed to connect to music.youtube.com/2001::1 (port 443) from /2409:8a6c:354:ddc1:a4d1:749b:9b81:4c72 (port 49056) after 10000ms: isConnected failed: ETIMEDOUT (Connection timed out)
12-24 15:39:36.030 10163 14628 E AndroidRuntime: 	at libcore.io.IoBridge.isConnected(IoBridge.java:283)
12-24 15:39:36.030 10163 14628 E AndroidRuntime: 	at libcore.io.IoBridge.connectErrno(IoBridge.java:192)
12-24 15:39:36.030 10163 14628 E AndroidRuntime: 	at libcore.io.IoBridge.connect(IoBridge.java:134)
12-24 15:39:36.030 10163 14628 E AndroidRuntime: 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
12-24 15:39:36.030 10163 14628 E AndroidRuntime: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
12-24 15:39:36.030 10163 14628 E AndroidRuntime: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
12-24 15:39:36.030 10163 14628 E AndroidRuntime: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
12-24 15:39:36.030 10163 14628 E AndroidRuntime: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
12-24 15:39:36.030 10163 14628 E AndroidRuntime: 	at java.net.Socket.connect(Socket.java:621)
12-24 15:39:36.030 10163 14628 E AndroidRuntime: 	at S5.n.e(SourceFile:6)
12-24 15:39:36.030 10163 14628 E AndroidRuntime: 	at O5.l.e(SourceFile:71)
12-24 15:39:36.030 10163 14628 E AndroidRuntime: 	at O5.l.c(SourceFile:136)
12-24 15:39:36.030 10163 14628 E AndroidRuntime: 	at O5.e.a(SourceFile:736)
12-24 15:39:36.030 10163 14628 E AndroidRuntime: 	at O5.a.a(SourceFile:60)
12-24 15:39:36.030 10163 14628 E AndroidRuntime: 	at P5.g.f(SourceFile:128)
12-24 15:39:36.030 10163 14628 E AndroidRuntime: 	at M5.b.a(SourceFile:153)
12-24 15:39:36.030 10163 14628 E AndroidRuntime: 	at P5.g.f(SourceFile:128)
12-24 15:39:36.030 10163 14628 E AndroidRuntime: 	at P5.a.a(SourceFile:589)
12-24 15:39:36.030 10163 14628 E AndroidRuntime: 	at P5.g.f(SourceFile:128)
12-24 15:39:36.030 10163 14628 E AndroidRuntime: 	at P5.a.a(SourceFile:153)
12-24 15:39:36.030 10163 14628 E AndroidRuntime: 	at P5.g.f(SourceFile:128)
12-24 15:39:36.030 10163 14628 E AndroidRuntime: 	at O5.i.g(SourceFile:97)
12-24 15:39:36.030 10163 14628 E AndroidRuntime: 	at O5.f.run(SourceFile:42)
12-24 15:39:36.030 10163 14628 E AndroidRuntime: 	... 3 more
12-24 15:39:36.030 10163 14628 E AndroidRuntime: 	Suppressed: java.net.SocketTimeoutException: failed to connect to music.youtube.com/31.13.106.4 (port 443) from /192.168.3.122 (port 43626) after 10000ms: isConnected failed: ETIMEDOUT (Connection timed out)
12-24 15:39:36.030 10163 14628 E AndroidRuntime: 		... 26 more
12-24 15:39:36.031 10163 14628 E AndroidRuntime: 	Caused by: android.system.ErrnoException: isConnected failed: ETIMEDOUT (Connection timed out)
12-24 15:39:36.031 10163 14628 E AndroidRuntime: 		at libcore.io.IoBridge.isConnected(IoBridge.java:274)
12-24 15:39:36.031 10163 14628 E AndroidRuntime: 		... 25 more
12-24 15:39:36.031 10163 14628 E AndroidRuntime: Caused by: android.system.ErrnoException: isConnected failed: ETIMEDOUT (Connection timed out)
12-24 15:39:36.031 10163 14628 E AndroidRuntime: 	at libcore.io.IoBridge.isConnected(IoBridge.java:274)
12-24 15:39:36.031 10163 14628 E AndroidRuntime: 	... 25 more
12-24 15:39:36.108 10163 14628 I Process : Sending signal. PID: 10163 SIG: 9

### OuterTune version

0.6.4

### Device & Android version

android 11

**Comment by inolie** [comment]
more crash log. also, I found that the error/crash does not occur when I completely turn off wifi or when the wifi is on but no internet connected. It ONLY happens when I am on an internet where youtube is blocked. 






--------- beginning of crash
12-24 16:08:37.833 25324 27397 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-23
12-24 16:08:37.833 25324 27397 E AndroidRuntime: Process: com.dd3boh.outertune, PID: 25324
12-24 16:08:37.833 25324 27397 E AndroidRuntime: t4.a: Connect timeout has expired [url=https://music.youtube.com/api/stats/playback?*************, connect_timeout=unknown ms]
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 	at N2.a.m(SourceFile:114)
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 	at O5.f.run(SourceFile:136)
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 	Suppressed: x5.g: [z0{Cancelling}@7ce8a68, Dispatchers.IO]
12-24 16:08:37.833 25324 27397 E AndroidRuntime: Caused by: java.net.SocketTimeoutException: failed to connect to music.youtube.com/2001::1 (port 443) from /2409:8a6c:354:ddc1:a4d1:749b:9b81:4c72 (port 37222) after 10000ms: isConnected failed: ETIMEDOUT (Connection timed out)
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 	at libcore.io.IoBridge.isConnected(IoBridge.java:283)
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 	at libcore.io.IoBridge.connectErrno(IoBridge.java:192)
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 	at libcore.io.IoBridge.connect(IoBridge.java:134)
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 	at java.net.Socket.connect(Socket.java:621)
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 	at S5.n.e(SourceFile:6)
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 	at O5.l.e(SourceFile:71)
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 	at O5.l.c(SourceFile:136)
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 	at O5.e.a(SourceFile:736)
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 	at O5.a.a(SourceFile:60)
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 	at P5.g.f(SourceFile:128)
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 	at M5.b.a(SourceFile:153)
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 	at P5.g.f(SourceFile:128)
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 	at P5.a.a(SourceFile:589)
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 	at P5.g.f(SourceFile:128)
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 	at P5.a.a(SourceFile:153)
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 	at P5.g.f(SourceFile:128)
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 	at O5.i.g(SourceFile:97)
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 	at O5.f.run(SourceFile:42)
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 	... 3 more
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 	Suppressed: java.net.SocketTimeoutException: failed to connect to music.youtube.com/199.59.148.20 (port 443) from /192.168.3.122 (port 45410) after 10000ms: isConnected failed: ETIMEDOUT (Connection timed out)
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 		... 26 more
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 	Caused by: android.system.ErrnoException: isConnected failed: ETIMEDOUT (Connection timed out)
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 		at libcore.io.IoBridge.isConnected(IoBridge.java:274)
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 		... 25 more
12-24 16:08:37.833 25324 27397 E AndroidRuntime: Caused by: android.system.ErrnoException: isConnected failed: ETIMEDOUT (Connection timed out)
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 	at libcore.io.IoBridge.isConnected(IoBridge.java:274)
12-24 16:08:37.833 25324 27397 E AndroidRuntime: 	... 25 more
12-24 16:08:37.875 25324 27397 I Process : Sending signal. PID: 25324 SIG: 9

**Comment by mikooomich** [comment]
Reproduce with debug apk from github actions please

**Comment by mikooomich** [comment]
Think this was fixed a whole ago...?
