### ISSUE TITLE
App crashes on unstable connection 

### ISSUE THREAD

**Issue by Kaptankaz** [OuterTune/OuterTune#70]
### Checklist

- [x] I am able to reproduce the bug with the [latest debug version](https://github.com/dd3boh/OuterTune/actions).
- [x] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

I have this problem when I am using unstable mobile network. When the internet suddenly goes out, the app crashes.

### Expected behavior

The music should stop and start again when the network is back on.

### Actual behavior

Application.crashed

### Logs

I don't know how to do it

### OuterTune version

0.6.2

### Android version

Android 13

**Comment by 14142000** [comment]
Yeah that explains why. As soon as I leave my house while playing music it crashes once and then as soon as I as soon as I leave my house while playing music, it crashes once and then as soon as I restart the music it's fine. I believe I have this issue also

**Comment by Lolozweipunktnull** [comment]
Yep, I have the same issue which is pretty annoying because it even occurs when you are playing only downloaded songs.

The logs of the crashes look all mostly like this:

FATAL EXCEPTION: DefaultDispatcher-worker-6
Process: com.dd3boh.outertune, PID: 19527
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:191)
	at java.net.SocketInputStream.read(SocketInputStream.java:143)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:983)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:947)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.-$$Nest$mprocessDataFromSocket(Unknown Source:0)
	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:236)
	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:218)
	at O5.l.g(SourceFile:104)
	at O5.l.c(SourceFile:139)
	at O5.e.a(SourceFile:736)
	at O5.a.a(SourceFile:60)
	at P5.g.f(SourceFile:128)
	at M5.b.a(SourceFile:153)
	at P5.g.f(SourceFile:128)
	at P5.a.a(SourceFile:589)
	at P5.g.f(SourceFile:128)
	at P5.a.a(SourceFile:153)
	at P5.g.f(SourceFile:128)
	at O5.i.g(SourceFile:97)
	at O5.f.run(SourceFile:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: java.net.SocketException: Connection reset
		... 23 more
	Suppressed: java.net.SocketException: Connection reset
		... 23 more
	Suppressed: java.net.SocketException: Connection reset
		... 23 more
	Suppressed: java.net.ConnectException: Failed to connect to music.youtube.com/216.58.214.78:443
		at O5.l.e(SourceFile:136)
		at O5.l.c(SourceFile:136)
		... 14 more
	Caused by: java.net.ConnectException: failed to connect to music.youtube.com/216.58.214.78 (port 443) from /10.111.222.1 (port 47980) after 10000ms: isConnected failed: ECONNABORTED (Software caused connection abort)
		at libcore.io.IoBridge.isConnected(IoBridge.java:347)
		at libcore.io.IoBridge.connectErrno(IoBridge.java:237)
		at libcore.io.IoBridge.connect(IoBridge.java:179)
		at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
		at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
		at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
		at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
		at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
		at java.net.Socket.connect(Socket.java:646)
		at S5.n.e(SourceFile:6)
		at O5.l.e(SourceFile:71)
		... 15 more
	Caused by: android.system.ErrnoException: isConnected failed: ECONNABORTED (Software caused connection abort)
		at libcore.io.IoBridge.isConnected(IoBridge.java:334)
		... 25 more
	Suppressed: java.net.SocketException: Connection reset
		at java.net.SocketInputStream.read(SocketInputStream.java:191)
		at java.net.SocketInputStream.read(SocketInputStream.java:143)
		at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:983)
		at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:947)
		at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:862)
		at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:835)
		at X5.e.w(SourceFile:50)
		at X5.e.w(SourceFile:136)
		at X5.E.m(SourceFile:23)
		at X5.E.u(SourceFile:1)
		at R5.r.a(SourceFile:16)
		at C3.l.c(SourceFile:211)
		at N5.b.a(SourceFile:176)
		at N5.d.a(SourceFile:19)
		at E2.q.run(SourceFile:160)
		... 3 more
	Suppressed: java.net.SocketException: Connection reset
		... 23 more
	Suppressed: java.net.SocketException: Connection reset
		... 23 more
	Suppressed: java.net.SocketException: Connection reset
		... 23 more
	Suppressed: java.net.SocketException: Connection reset
		... 23 more
	Suppressed: java.net.SocketException: Connection reset
		... 23 more
	Suppressed: x5.g: [z0{Cancelling}@341e1c4, Dispatchers.IO]

**Comment by Kaptankaz** [comment]
> Evet, ben de aynı sorunu yaşıyorum ve oldukça can sıkıcı bir durum çünkü bu sorun yalnızca indirdiğiniz şarkıları çaldığınızda bile ortaya çıkıyor.
> 
> Kazaların kayıtları genel olarak şöyle görünüyor:
> 
> ÖLÜMCÜL İSTİSNA: DefaultDispatcher-worker-6 İşlem: com.dd3boh.outertune, PID: 19527 java.net.SocketException: Bağlantı sıfırlandı java.net.SocketInputStream.read(SocketInputStream.java:191) adresinde java.net.SocketInputStream.read(SocketInputStream.java:143) adresinde com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:983) adresinde com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:947) adresinde com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.-$$Nest$mprocessDataFromSocket(Bilinmeyen Kaynak:0) at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:236) at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:218) at O5.lg(KaynakDosyası:104) at O5.lc(KaynakDosyası:139) at O5.ea(KaynakDosyası:736) at O5.aa(KaynakDosyası:60) at P5.gf(KaynakDosyası:128) at M5.ba(KaynakDosyası:153) at P5.gf(KaynakDosyası:128) P5.aa(KaynakDosyası:589) adresinde P5.gf(KaynakDosyası:128) adresinde P5.aa(KaynakDosyası:153) adresinde P5.gf(KaynakDosyası:128) adresinde O5.ig(KaynakDosyası:97) adresinde O5.f.run(KaynakDosyası:42) adresinde java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) adresinde java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) adresinde java.lang.Thread.run(Thread.java:1012) adresinde Bastırıldı: java.net.SocketException: Bağlantı sıfırlandı ... 23 daha Bastırıldı: java.net.SocketException: Bağlantı sıfırlandı ... 23 daha Bastırıldı: java.net.SocketException: Bağlantı sıfırlandı ... 23 daha Bastırıldı: java.net.ConnectException: music.youtube.com/216.58.214.78:443 adresine bağlanılamadı O5.le(SourceFile:136) adresinde O5.lc(SourceFile:136) adresinde ... 14 daha Nedeni: java.net.ConnectException: 10000 ms sonra /10.111.222.1 (port 47980) adresinden music.youtube.com/216.58.214.78 (port 443) adresine bağlanılamadı: isConnected başarısız oldu: ECONNABORTED (Yazılım bağlantının kesilmesine neden oldu) libcore.io.IoBridge.isConnected(IoBridge.java:347) adresinde libcore.io.IoBridge.connectErrno(IoBridge.java:237) at libcore.io.IoBridge.connect(IoBridge.java:179) at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142) at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390) at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230) at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212) java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436) adresinde java.net.Socket.connect(Socket.java:646) adresinde S5.ne(SourceFile:6) adresinde O5.le(SourceFile:71) adresinde ... 15 daha fazla Neden: android.system.ErrnoException: isConnected başarısız oldu: ECONNABORTED (Yazılım bağlantının kesilmesine neden oldu) libcore.io.IoBridge.isConnected(IoBridge.java:334) adresinde ... 25 daha fazla Bastırıldı: java.net.SocketException: Bağlantı sıfırlandı java.net.SocketInputStream.read(SocketInputStream.java:191) adresinde java.net.SocketInputStream.read(SocketInputStream.java:143) adresinde com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:983) adresinde com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:947) adresinde com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:862) adresinde com.android.org.conscrypt.ConscryptEngineSocket $SSLInputStream.read(ConscryptEngineSocket.java:835) adresinde X5.ew(KaynakDosyası:50) adresinde X5.ew(KaynakDosyası:136) adresinde X5.Em(KaynakDosyası:23) X5.Eu(KaynakDosyası:1) adresinde R5.ra(KaynakDosyası:16) adresinde C3.lc(KaynakDosyası:211) adresinde N5.ba(KaynakDosyası:176) adresinde N5.da(KaynakDosyası:19) adresinde E2.q.run(KaynakDosyası:160) adresinde ... 3 tane daha Bastırılmış: java.net.SocketException: Bağlantı sıfırlandı ... 23 tane daha Bastırılmış: java.net.SocketException: Bağlantı sıfırlandı ... 23 tane daha Bastırılmış: java.net.SocketException : Bağlantı sıfırlandı ... 23 tane daha Bastırılmış : java.net.SocketException : Bağlantı sıfırlandı ... 23 tane daha Bastırılmış: x5.g: [z0{İptal}@341e1c4, Dispatchers.IO]

Also sometimes I get an error with error number 2003(I think) and the whole playlist is reset

**Comment by mikooomich** [comment]
@mattcarter11 is this issue the same one you referenced here? https://github.com/DD3Boh/OuterTune/pull/63/commits/3884d30a7a3e92cb405c1f1d88b14ae039483745

**Comment by Kaptankaz** [comment]
> @mattcarter11bu sorun burada sorunlarla aynı mı [?](https://github.com/DD3Boh/OuterTune/commit/3884d30a7a3e92cb405c1f1d88b14ae039483745)

Yes, Same problem
